name: Build Kernel

on:
  push:
    branches:
      - master  # شغّل عند أي تحديث للفرع الرئيسي
  workflow_dispatch:  # للسماح بالتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc build-essential flex bison libssl-dev libncurses5-dev ccache clang lld lldb

      - name: Set up GCC toolchain
        run: |
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64.git gcc64
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm.git gcc32
          export PATH=$PWD/gcc64/bin:$PWD/gcc32/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Compile the Kernel
        run: |
          make O=out ARCH=arm64 a5xelte_defconfig  # استبدل بالكونفيج المناسب لجهازك
          make -j$(nproc) O=out ARCH=arm64

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v3
        with:
          name: Kernel-Image
          path: out/arch/arm64/boot/Image.gz-dtb
